In [1]:
#Name:Jethava Aashtha
#Enrollment No:216270307089

'''2.1->to convert a list of numeric values into a one-dimensional NumPy 
array'''
import numpy as np
numeric_values = [1, 2, 3, 4, 5]

# Convert the list to a one-dimensional NumPy array
array = np.array(numeric_values)
print(array)


[1 2 3 4 5]


In [2]:
'''2.2-> to create a 3x3 matrix with values ranging from 2 to 10'''
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
'''2.3->to append values at the end of an array
'''
import numpy as np
arr = np.array([1, 2, 3])
print("Array:",arr)
# Append values to the end of the array
arr = np.append(arr,[4, 5, 6])
print("Array after Appending values",arr)


Array: [1 2 3]
Array after Appending values [1 2 3 4 5 6]


In [4]:
'''2.4->to create another shape from an array without changing its data(3*2 
to 2*3)'''
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
# Create a 2x3 array from the same data
b = np.reshape(a, (2, 3))
print("original array:\n",a)
print("the new array:\n",b)


original array:
 [[1 2]
 [3 4]
 [5 6]]
the new array:
 [[1 2 3]
 [4 5 6]]
